### ISSUE TITLE
Metrics Discovery Registrar is not sending messages to nats

### ISSUE THREAD

**Issue by iplay88keys** [cloudfoundry/metrics-discovery-release#9]
It seems we have found a bug with the `metrics-discovery-registrar`. We weren't getting nats messages of scrape configs from the Router VM until we restarted the `metrics-discovery-registrar` process. It seems like a timing issue from when the `metrics-discovery-registrar` process came up compared to the nats process as we were seeing nats messages for scrape configs from the blobstore and database VMs. Restarting the `metrics-discovery-registrar` process on the Router gave us scrape config messages instantly. Maybe there needs to be a retry built into the `metrics-discovery-registrar` process around the nats connection?

**Comment by iplay88keys** [comment]
We noticed this issue when reviewing the scrape config generated by the `config-generator`. We noticed that the Router VM's metric scrape configs were not showing up in that file. We looked into the logs for the `metrics-discovery-registrar` on the Router VM, but we didn't see any errors.

We downloaded the nats cli onto the VM where we were running the `config-generator` process. We ran `nats sub metrics.scrape_targets` and saw that only the `metrics-discovery-registrar` processes on the blobstore and database VMs were sending nats messages. We then restarted the `metrics-discovery-registrar` process on the Router VM in a different terminal and started seeing the nats messages show up from the Router VM's `metrics-discovery-registrar` process.

**Comment by kcboyle** [comment]
We've been trying to work on this issue and found a way to reliably recreate the behavior:

on the router vm:
1. Stop metrics-discovery-registrar
1. delete `/var/vcap/data/metrics-agent/metric_targets.yml` (or move if this makes you nervous)
1. `monit restart metrics-discovery-registrar`
1. `monit restart metrics-agent`

Command to check the scrape targets (router, specifically in the grep is missing):
```
./nats sub --user nats --password 'N1VfEV5qsvlV8a9gapwjviqWv9uMta' --tlscert /var/vcap/jobs/metrics-discovery-registrar/config/certs/nats.crt --tlsca /var/vcap/jobs/metrics-discovery-registrar/config/certs/nats_ca.crt --tlskey /var/vcap/jobs/metrics-discovery-registrar/config/certs/nats.key --server nats.service.cf.internal:4224 metrics.scrape_targets | grep router
```

To fix:
`monit restart metrics-discovery-registrar`

**Comment by kcboyle** [comment]
We've tried putting logging in multiple places in fileprovider and the registrar, and everything seems to be reading from the correct file as far as we can tell. We even tried changing the file_provider to open and close an actual file, thinking maybe go wasn't closing the file properly ([here]https://github.com/cloudfoundry/metrics-discovery-release/blob/develop/src/internal/target/file_provider.go#L57)) but that gave no difference.

**Comment by kcboyle** [comment]
Something super fascinating: if you restart `metrics-discovery-registrar`, and then edit `vi /var/vcap/data/metrics-agent/metric_targets.yml`, things appear to update as expected. HOWEVER, as soon as you edit `vim /var/vcap/data/metrics-agent/metric_targets.yml`, it will not update again until the process is restarted. 

Looking into this a little more: Rather than changing the file in place (vi) it creates a tmp file and then overwrites the original file (vim)

```
unsafe:
    unrestricted_volumes:
    - path: "/var/vcap/**/**/metric_targets.yml"
      mount_only: true
```

Because we are pulling in this exact file, it appears that we are pulling in the file with the specific `Inode` when the process was started.
SO, the next question  is "how is the metrics-agent updating this file?" (see an example of this in the attachment). When we are pulling in a singular file (above), we are using the file with the specific Inode identifier.

- Pulling in all directories for `/var/vcap` to look at (instead of the one file)
  - CON: we're pulling in a LOT. This is a security problem(**maybe?**)
  - PRO: changing one config file, and no other changes to metrics-discovery-registrar
- have metrics-agent update this file differently (update in place, rather than with a temp file)
  - CON: potentially a less safe way to write files, also, don't know if it's possible in metrics-agent
  - PRO: we keep the files pulled in tight and clean
![Screen Shot 2021-05-26 at 1 43 27 PM](https://user-images.githubusercontent.com/1361223/119849904-e41cf280-bec1-11eb-9bee-827e5874b776.png)

**Comment by kcboyle** [comment]
We ran some tests against metrics-agent, and found that it is not a problem with how go is writing. Took a simple main and ran it in the `router` vm, testing the inode before and after, as well as printing what `go` thinks the inode is. Everything appears to work as expected:
![Screen Shot 2021-05-26 at 4 02 15 PM](https://user-images.githubusercontent.com/1361223/119850845-c1d7a480-bec2-11eb-91b4-6f8bbad953c4.png)

**Comment by kcboyle** [comment]
However, we can change the config for `/var/vcap/jobs/metrics-discovery-registrar/config/bpm.yml` FROM:
```processes:
- name: metrics-discovery-registrar
  executable: "/var/vcap/packages/metrics-discovery-registrar/discovery-registrar"
  unsafe:
    unrestricted_volumes:
    - path: "/var/vcap/**/**/metric_targets.yml"
      mount_only: true```
TO
```processes:
- name: metrics-discovery-registrar
  executable: "/var/vcap/packages/metrics-discovery-registrar/discovery-registrar"
  unsafe:
    unrestricted_volumes:
    - path: "/var/vcap/**/**"
      mount_only: true```

And we are unable to recreate the issue. What do y'all think about this?

**Comment by Benjamintf1** [comment]
sounds reasonable to me tbh.

**Comment by Benjamintf1** [comment]
LMK if that fixes things for you. Should have just cut a release.

**Comment by Benjamintf1** [comment]
This should work now we think? feel free to re-open if not.
